### ISSUE TITLE
Change app namespace

### ISSUE THREAD

**Issue by Awkan** [Nekland/Neko-Wiki#17]
Use an explicit namespace for NekoWiki.    
That is to say:
- [ ] Rename `src/App` as `src/Nekland/NekoWiki`
- [ ] Change all namespaces

**Comment by Nek-** [comment]
About the folder renaming, it's not an obligation. You may have `src/NekoWiki` and specify in `composer.json` that you want the namespace `Nekland\NekoWiki` for this folder.
